# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
machine: true
jobs:
  test-and-report:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: test
          command:
            cd ui-tests-8a-pl && mvn clean test
      - run:
          when: always
          name: report
          command:
            cd ui-tests-8a-pl && mvn allure:report
      - store_artifacts:
          path: /home/circleci/project/ui-tests-8a-pl/target/site/allure-maven-plugin
          destination: allure-report


workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  sample:
    jobs:
      - test-and-report
